# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdp-cli" do
  name "pdp-cli"
  desc "CLI for Discovery 2.x"
  homepage "https://github.com/diego-granados/pdp-cli-releases-test"
  version "0.2.0-beta14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "discovery"

  on_macos do
    on_intel do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_darwin_amd64.tar.gz"
      sha256 "2ed9f0f754b23de94729297183c0bf950b601cab4a2840ce906dc8995fbb1857"
    end
    on_arm do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_darwin_arm64.tar.gz"
      sha256 "b22270958a8680bea81f15a6bfb3dc35a9d9162a332138c0ea2c02b7b4c57209"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_linux_amd64.tar.gz"
      sha256 "64724f04cdcecbaeaaf20a64171f0f2193c08033212092e64ef1cc4641c34e00"
    end
    on_arm do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_linux_arm64.tar.gz"
      sha256 "d9cbf2a371154f2559c0dbde9ed448e3f1b6fd8bfcbf881d8978af5efef4f0d2"
    end
  end

  # No zap stanza required
end
