# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdp-cli" do
  name "pdp-cli"
  desc "CLI for Discovery 2.x"
  homepage "https://github.com/diego-granados/pdp-cli-releases-test"
  version "0.2.0-beta15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "discovery"

  on_macos do
    on_intel do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_darwin_amd64.tar.gz"
      sha256 "6f608b88001f62644cb2d2c92014104c2fa87617b715cc4056991c8f02b100ee"
    end
    on_arm do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_darwin_arm64.tar.gz"
      sha256 "70041159870dfbc48ff6297802c035e8243e6dd682691d74090068b5ed8f189c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_linux_amd64.tar.gz"
      sha256 "d13b4ffbd6632916496384feb11c95315edfd7ed586111540c06c156ab17a30d"
    end
    on_arm do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_linux_arm64.tar.gz"
      sha256 "d03ba7523330c0b730c18779ba2a32d97d608bf7afce80eafe79c39338177497"
    end
  end

  # No zap stanza required
end
